### ISSUE TITLE
useQuery의 반환값 중 isSuccess

### ISSUE THREAD

**Issue by zigsong** [zereight/simple-react-query#6]
```jsx
return {
    refetch,
    isLoading,
    isError,
    data,
    error,
    setData,
    isSuccess: !isError,
    clearRefetchInterval,
    isFetched
  };
```

`isSuccess: !isError`에 의문

`isFetched`가 false라면 `error`가 `null`이어도 `isSuccess`는 false지 않을까요 👀

**Comment by zereight** [comment]
다시 설명해주실 수 있나요?
살짝 헷갈리긴한데 isError값을 !!error로 바꾸기만 하면 논리적으로 해결되는 상황인건가요?!

**Comment by zigsong** [comment]
아직 `fetching`중인 상태라면 `error`가 `isError`도 `false`고 `isSuccess`도 `false`이지 않을까요?!

**Comment by zereight** [comment]
`fetching`중인 상태는 `isLoading`이 담당하고 있습니당.
혹시 `isFetched`가 false이면 fetching 중인 상태라고 해석을 하신건가요!

**Comment by zigsong** [comment]
음... 🤔
처음 `useQuery`가 호출되었을 때 반환값은 `isError`: `false`, `isSuccess`: `true`일 텐데, 아직 로딩 중인지 fetch완료인지 알 수 없는 상태(`error`, `success`까지는 가지도 않음)에서 `isSuccess`값은 다짜고짜 `true`를 리턴하게 되는 게 아닌지 생각이 들어서용

**Comment by zereight** [comment]
아아 그 뜻이군요! 이해했어요. 확실히 그럴 수 있겠네요! isSuccess 조건문을 한번 수정해보겠습니다. 수정하고 한번더 피드백 해줄 수 있으시면 해주세욯ㅎㅎ

**Comment by zereight** [comment]
@zigsong  

[commit](https://github.com/zereight/simple-react-query/commit/86e8a41029a0fd6ced7a127d8a57516d2b7ff4a6)

- isError와 isSuccess에 isFetched라는 조건을 달았습니다.
- isFetched가 요청이 성공했을 시에만 true가 되고 있었는데 error일때도 fetch로 판단하도록 변경했습니다.

더 보완해야할게 있다면 알려주세용!

**Comment by zereight** [comment]
close
